### ISSUE TITLE
Feature Request: encrypt and decrypt note

### ISSUE THREAD

**Issue by dasmaetthes** [owncloud/notes#201] opened 2016-02-16 19:01 UTC
Would be nice to have the possibility to encrypt and decrypt a note like you can do in [QOwnNotes ](http://www.qownnotes.org)and having the possibility to share/sync the key over different devices.

**Comment by Henni** [comment] 2016-02-17 10:20
duplicate of https://github.com/owncloud/notes/issues/200, please continue discussion over there

**Closed by Henni** 2016-02-17 10:20 UTC

**Comment by pbek** [comment] 2016-03-19 12:22
As a side note: [QOwnNotes](http://www.qownnotes.org) now uses AES-256 encryption.
