### ISSUE TITLE
Can't find OwnCloud Notes in 8.2.3

### ISSUE THREAD

**Issue by n00b12345** [owncloud/notes#216] opened 2016-04-03 11:30 UTC
I just updated OC from 8.2 to 8.2.3 and can't find OwnCloud Notes. Has the app been removed from this particular version?

**Comment by slashrsm** [comment] 2016-04-06 09:36
Updates usually disabled 3rd party apps. I re-enabled and now all my notes are gone. I can still find the files in "Notes" folder.

**Comment by slashrsm** [comment] 2016-04-06 09:44
Investigating this further I discovered that I get 404 on the two routes that return list of notes (/apps/notes/notes) and content of the current note (/apps/notes/notes/[note ID]). This happened after upgrade to 8.2.3. It was working without any problems with 8.2.2.

**Comment by Henni** [comment] 2016-04-06 10:16
@n00b12345 can't reproduce your issue

@slashrsm your issue was fixed by #217

**Closed** 2016-04-06 10:26 UTC

**Comment by slashrsm** [comment] 2016-04-06 11:12
@Henni Just figured that out by myself too. Thanks!
