### ISSUE TITLE
Starting title with an emoticon is not handled gracefully

### ISSUE THREAD

**Issue by phedlund** [owncloud/notes#75] opened 2015-01-05 22:44 UTC
Create a new note and add an emoticon 😀 as the first character. The note is saved, but if another note is selected the emoticon note can never be selected again. The title appears as 'false'.

**Comment by olssonr** [comment] 2015-01-06 15:59
I also got this problem. Only way I managed to solve it was to go into the database and delete the row corresponding to that file name. The fileid was the number at the end of the url in the notes app. You can also see the path and name of the files in the table so it was easy to find.

**Comment by LukasReschke** [comment] 2015-01-25 09:18
That works fine on current master for me. What DB are you using?

**Comment by olssonr** [comment] 2015-01-26 20:02
@LukasReschke I use mysql. Let me know if you need further information.

**Comment by LukasReschke** [comment] 2015-01-26 20:07
Can you please run the following query on the MySQL server and post the results?

```sql
SHOW TABLE STATUS FROM name_of_owncloud_db;
```

**Comment by olssonr** [comment] 2015-01-26 20:31
Sure, here it is.

```
mysql> SHOW TABLE STATUS FROM owncloud;
+------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------+----------+----------------+---------+
| Name                         | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation | Checksum | Create_options | Comment |
+------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------+----------+----------------+---------+
| oc_activity                  | InnoDB |      10 | Compact    | 1103 |            282 |      311296 |               0 |       180224 |  11534336 |            976 | 2014-11-30 21:32:58 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_activity_mq               | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |        49152 |  11534336 |              1 | 2014-11-30 21:32:59 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_appconfig                 | InnoDB |      10 | Compact    |   85 |            192 |       16384 |               0 |        32768 |  11534336 |           NULL | 2014-11-30 21:32:59 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_clndr_calendars           | InnoDB |      10 | Compact    |    5 |           3276 |       16384 |               0 |            0 |  11534336 |              7 | 2014-11-30 21:32:59 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_clndr_objects             | InnoDB |      10 | Compact    |   87 |           2259 |      196608 |               0 |            0 |  11534336 |            194 | 2014-11-30 21:32:59 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_clndr_repeat              | InnoDB |      10 | Compact    |  443 |            110 |       49152 |               0 |            0 |  11534336 |          57635 | 2014-11-30 21:32:59 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_clndr_share_calendar      | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:32:59 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_clndr_share_event         | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:32:59 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_contacts_addressbooks     | InnoDB |      10 | Compact    |    3 |           5461 |       16384 |               0 |        16384 |  11534336 |              4 | 2014-11-30 21:32:59 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_contacts_cards            | InnoDB |      10 | Compact    |  122 |           1074 |      131072 |               0 |        16384 |  11534336 |            590 | 2014-11-30 21:33:00 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_contacts_cards_properties | InnoDB |      10 | Compact    |  658 |            124 |       81920 |               0 |        81920 |  11534336 |           4267 | 2014-11-30 21:33:00 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_documents_invite          | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:33:00 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_documents_member          | InnoDB |      10 | Compact    |    3 |           5461 |       16384 |               0 |            0 |  11534336 |              4 | 2014-11-30 21:33:01 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_documents_op              | InnoDB |      10 | Compact    |  231 |            354 |       81920 |               0 |        16384 |  11534336 |            240 | 2014-11-30 21:33:01 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_documents_revisions       | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:33:01 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_documents_session         | InnoDB |      10 | Compact    |    3 |           5461 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:33:01 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_file_map                  | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |        16384 |  11534336 |           NULL | 2014-11-30 21:33:01 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_filecache                 | InnoDB |      10 | Compact    | 1019 |            273 |      278528 |               0 |       311296 |  11534336 |           1690 | 2014-11-30 21:33:01 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_files_trash               | InnoDB |      10 | Compact    |   14 |           1170 |       16384 |               0 |        49152 |  11534336 |             47 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_gallery_sharing           | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_group_admin               | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |        16384 |  11534336 |           NULL | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_group_user                | InnoDB |      10 | Compact    |    2 |           8192 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_groups                    | InnoDB |      10 | Compact    |    1 |          16384 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_jobs                      | InnoDB |      10 | Compact    |    6 |           2730 |       16384 |               0 |        16384 |  11534336 |            410 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_locks                     | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |            0 |  11534336 |              1 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_lucene_status             | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |        16384 |  11534336 |           NULL | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_mimetypes                 | InnoDB |      10 | Compact    |   21 |            780 |       16384 |               0 |        16384 |  11534336 |             26 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_pictures_images_cache     | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_preferences               | InnoDB |      10 | Compact    |   31 |            528 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_privatedata               | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |            0 |  11534336 |              1 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_properties                | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |        16384 |  11534336 |              1 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_share                     | InnoDB |      10 | Compact    |    6 |           2730 |       16384 |               0 |        49152 |  11534336 |              7 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_share_external            | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |        32768 |  11534336 |              1 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_storages                  | InnoDB |      10 | Compact    |    6 |           2730 |       16384 |               0 |        16384 |  11534336 |              7 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_users                     | InnoDB |      10 | Compact    |    3 |           5461 |       16384 |               0 |            0 |  11534336 |           NULL | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_vcategory                 | InnoDB |      10 | Compact    |   35 |            468 |       16384 |               0 |        49152 |  11534336 |             37 | 2014-11-30 21:33:02 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
| oc_vcategory_to_object       | InnoDB |      10 | Compact    |   22 |            744 |       16384 |               0 |        16384 |  11534336 |           NULL | 2014-11-30 21:33:03 | NULL        | NULL       | utf8_bin  |     NULL |                |         |
+------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------+----------+----------------+---------+
37 rows in set (0.06 sec)
```

**Comment by Raydiation** [comment] 2015-02-18 14:59
Works for me too

**Comment by Henni** [comment] 2015-10-20 15:10
I also can't reproduce this.
Closing it for now. Please reopen it if this still occurs for you.

**Closed by Henni** 2015-10-20 15:10 UTC
Labels: bug
