### ISSUE TITLE
"New Note" button only displayed on hover

### ISSUE THREAD

**Issue by tchncs** [owncloud/notes#173] opened 2015-11-03 20:02 UTC
The button for a new note is only displayed on hover in ownCloud 0.8.2 (is this wanted?).
The **+** is so small, i found it as i cutted the screenshots, i thought there is nothing.
![](https://files.tchncs.de/Images/Random/Screenshots/oc-notes-issue.png)

![](https://files.tchncs.de/Images/Random/Screenshots/oc-notes-issue_hover.png)
****
The word-counter is also very, very small and so light-grey, so i found it randomly also.
(But if you know its there, its not a big problem anymore i think... - the hover thing has more priority)
![](https://files.tchncs.de/Images/Random/Screenshots/oc-notes-issue_full.png)

Regards and thank you for creating the Notes app :-)

**Comment by Henni** [comment] 2015-11-03 20:07
This is intended behaviour introduced by @jancborchardt 

I'll probably darken the font-color of the word counter.

**Comment by jancborchardt** [comment] 2015-11-04 12:56
I think the word counter is fine, as the design is exactly intended as @tchncs described it:

> The word-counter is also very, very small and so light-grey, so i found it randomly also. But if you know its there, its not a big problem anymore i think

For »+ New note«, the reason we don’t show the full title always is so that it’s distinguished from the notes which always have text. Otherwise it would look too much like a note itself. Does that make sense?

**Comment by tchncs** [comment] 2015-11-04 21:16
>For »+ New note«, the reason we don’t show the full title always is so that it’s distinguished from the notes which always have text.

I really understand and agree with your point.
Maybe it will helpful für new users to replace it with a little pen for example?
The big blank, but clickable area could confuse much people - it looks "unfinish".
This is just a thought to it, nothing more. :-)

Oh, and one more thing: the browsers scrollbar is always visible, maybe this is really a thing thats not wanted ;)

**Comment by jancborchardt** [comment] 2015-11-13 07:33
> Oh, and one more thing: the browsers scrollbar is always visible, maybe this is really a thing thats not wanted ;)

Good point, yeah. Do you have experience with auto-hiding scrollbars and only showing them on scrolling or on mouse move? A pull request implementing that in core would be great! :)

**Comment by Henni** [comment] 2015-11-24 11:37
fixed by #177

**Closed by Henni** 2015-11-24 11:37 UTC
